### ISSUE TITLE
ahoy install should automagically fix the site Uuid

### ISSUE THREAD

**Issue by simesy** [govCMS/govcms8-scaffold#10]
Ahoy install installs drupal, then imports from the config directory.
This will usually fail because of the site UUID (does it actualy work for anyone else?)

It would be good if this command would fix the site UUID before importing.

```
[si] {master} $ ahoy install

 // You are about to DROP all tables in your 'drupal' database. Do you want to
 // continue?: yes.

 [notice] Starting Drupal installation. This takes a while.
 [success] Installation complete.  User name: admin  User password: 9hPTH8Vgtu
 [success] No pending updates.
 [success] Cache rebuild complete.
+------------+---------------------------------------------------------------------------------------+-----------+
| Collection | Config                                                                                | Operation |
+------------+---------------------------------------------------------------------------------------+-----------+
|            | acmatheme.settings                                                                    | Create    |
|            | adminimal_theme.settings                                                              | Create    |
|            | block.block.acmaadminimal_pagetitle                                                   | Create    |
|            | block.block.acmaadminimal_tabs                                                        | Create    |
...

 // Import the listed configuration changes?: yes.

 [error]  Drupal\Core\Config\ConfigImporterException: There were errors validating the config synchronization.
Site UUID in source storage does not match the target storage.
Entities exist of type <em class="placeholder">Shortcut link</em> and <em class="placeholder">Shortcut set</em> <em class="placeholder">Default</em>. These entities need to be deleted before importing. in Drupal\Core\Config\ConfigImporter->validate() (line 737 of /app/web/core/lib/Drupal/Core/Config/ConfigImporter.php).

```

**Comment by tobybellwood** [comment]
you're probably the first person to do an ahoy install into a site that has config but no database!  Usually the (provisioned) environments come with a vanilla db to download and build from - and the config all matches - once your site is forklifted, the db and UUIDs will match - but I take the point that (in your case) there is validity in forcing the db to match the config UUIDs - can this be done in Drupal?

**Comment by stooit** [comment]
You can run a `ahoy drush cset "system.site" uuid <insert_uuid_here>`

The shortcut link issue is also well known when installing a fresh site using configuration - new entities get created on fresh site install which conflict with the shortcut set in configuration. You'll need to run
`ahoy drush ev '\Drupal::entityManager()->getStorage("shortcut_set")->load("default")->delete();'`

After this you should be able to import config against a blank install.

**Comment by tobybellwood** [comment]
~`cat /app/config/default/system.site.yml | grep uuid | awk '{print $2}' | xargs -n1 drush cset "system.site" uuid` - not so sure it'll be used that often tho'~

**Comment by tobybellwood** [comment]
_rereads `ahoy cim` command and scrubs his last comment_

use `ahoy cim`

**Comment by simesy** [comment]
What you guys mean to say is `ahoy install` is not intended to be a shortcut/replacement for `drush site-install govcms`, yeah?

Or in other words: Is there ever a time when you would run `ahoy install` after a site has been initially installed? Guessing no, in which case we can close the issue.

**Comment by simesy** [comment]
On a related note, `ahoy up` is also doing too much for me. Ideally it should just start my local docker, but since it also runs `deploy-govcms`, and my local database had some content in it from another task, it caused config import step to fail. I personally think that `ahoy deploy-govcms` should not be running under these tasks `ahoy up` and `ahoy install` as they couple a lot of stuff together.

I realise these command names are semantic juggling, but in general it should be possible to use the building blocks by themselves one way or another without remembering complex docker-compose arguments.
