### ISSUE TITLE
Error when saving nodes with menu item

### ISSUE THREAD

**Issue by OPCIT** [govCMS/govcms8-scaffold#13]
Not sure if this relates to the scaffold or lagoon builds, but in the past week we've started getting the following error when adding a menu to a node (or via structure/menus) on local dev's.

**_General error: 1364 Field &#039;revision_id&#039; doesn&#039;t have a default value: INSERT INTO {menu_link_content_data}_**

Running 'ahoy drush entup' produces the following:

**_The following updates are pending:
media entity type : 
The Authored by field needs to be updated.
taxonomy_term entity type : 
The Language field needs to be updated.
The Name field needs to be updated.
The Description field needs to be updated.
The Changed field needs to be updated.
menu_link_content entity type : 
The Custom menu link entity type needs to be updated.
The Revision ID field needs to be uninstalled.
The Default revision field needs to be uninstalled.
The Revision translation affected field needs to be uninstalled.
The Revision create time field needs to be uninstalled.
The Revision user field needs to be uninstalled.
The Revision log message field needs to be uninstalled.
>  [error]  Drupal\Core\Entity\EntityStorageException: The SQL storage cannot change the schema for an existing entity type (menu_link_content) with data. in Drupal\Core\Entity\Sql\SqlContentEntityStorageSchema->onEntityTypeUpdate() (line 347 of /app/web/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorageSchema.php).> 
 [success] Finished performing updates._**

**Comment by simesy** [comment]
Usually this is a Drupal update issue (there are a few instances of this occuring from Drupal 8.2 -> 8.3).

This project is just about setting up new GovCMS d8 projects, so if this continues to be a problem please open a new ticket against https://github.com/govCMS/govCMS8/issues
and drop a link back here and I'll follow up over there.
