### ISSUE TITLE
Update doco - add note on how to pull latest docker images

### ISSUE THREAD

**Issue by joshua-graham-adelphi** [govCMS/govcms8-scaffold#17]

**Comment by joshua-graham-adelphi** [comment]
Update for Windows commands based on "ahoy pull"

**Comment by simesy** [comment]
@joshua-graham-adelphi  this documentation has moved to the wiki.

**Comment by joshua-graham-adelphi** [comment]
@simesy is this the wiki or is that only govcms7 ?

https://github.com/govCMS/govCMS/wiki

(specifically https://github.com/govCMS/govCMS/wiki/An-all-in-one-developer-guide-govCMS-SaaS#image-updates )

**Comment by simesy** [comment]
I prefer D8 with callouts to D7. I'm going to do a new Windows page for the wiki, so if you want to chuck it in An-all-in-one-developer-guide-govCMS-SaaS#image-updates (which was contributed by Tim Fletcher i think...) I'll sweep it up and bring it into the general Windows doc.

**Comment by simesy** [comment]
There are a few things in your PR though - how to alias if you can't use ahoy for eg. I mmmmmight split it up a bit. Just chuck it in the all in one (or  in troubleshooting). but I don't think it's d7/d8 specific from first glance.

**Comment by simesy** [comment]
Oh. Yes only one wiki. D8 wiki points to D7 wiki now.
