### ISSUE TITLE
Send email from inside docker container in development (without a SMTP server)?

### ISSUE THREAD

**Issue by joshua-graham-adelphi** [govCMS/govcms8-scaffold#40]
Wondering what the recommended way is to send email from a docker container during development or a simple UAT/TEST site.

Usually in a LAMP stack, Drupal can use the linux OS sendmail program however I don't think it works inside the docker container?

**Comment by simesy** [comment]
It can send to mailhog but I don't know off-hand the configuration.

**Comment by stooit** [comment]
mailhog should be enabled and functional ootb - simply visit http://mailhog.docker.amazee.io/ and you should see all captured mail sent via sendmail.

To test:
```
ahoy cli
echo "Subject: sendmail test" | sendmail -v my@email.com
```

The response should be from mailhog, e.g
```
[<-] 220 mailhog.example ESMTP MailHog
[->] HELO 8671cd3e3070
[<-] 250 Hello 8671cd3e3070
[->] MAIL FROM:<root@8671cd3e3070>
[<-] 250 Sender root@8671cd3e3070 ok
[->] RCPT TO:<my@email.com>
[<-] 250 Recipient my@email.com ok
[->] DATA
[<-] 354 End data with <CR><LF>.<CR><LF>
[->] Received: by 8671cd3e3070 (sSMTP sendmail emulation); Sat, 01 Feb 2020 01:38:43 +0000
[->] From: "root" <root@8671cd3e3070>
[->] Date: Sat, 01 Feb 2020 01:38:43 +0000
[->] Subject: sendmail test
[->]
[->] .
[<-] 250 Ok: queued as F7IgY2pfpfTbpspAFu5OKR9yBsHSPvHqXkomn7i9mOM=@mailhog.example
[->] QUIT
[<-] 221 Bye
```

And an appropriate email captured in mailhog. I have taken an action item to update docs to reflect this. Please reopen this issue if you find sendmail is not redirecting to mailhog.
