### ISSUE TITLE
Environment UI Module

### ISSUE THREAD

**Issue by njwesterman** [govCMS/govcms8-scaffold#47]
Hi there,

I work for an agency that is on the govCMS8 SaaS platform. I have been advised by a govCMS service representative that my issue cannot be solved by the govCMS service desk and they have sent me a link to raise an issue here.

There is a module called Environment UI indicator that colors the toolbar depending on which environment you are on. 

It is causing great confusion to our editors and testers, as either the text is unreadable, the colors don't match the system as one would expect, and it shows different colors if you are logged in to production via the master URL, or our custom master alias URL. 

What we decided to do was implement our own version that showed a dark green for local, pastel green for dev, pastel yellow for test, pastel red for both master URLs and bright red for public domain (which has login screen hidden, but done for completeness) - the text color changes between white or black, depending on accessibility for the systems color scheme. 

This solution has been working just great, and the environment UI module had been disabled in our configuration. When the Environment UI module is turned on, it overrides our settings and the standard implementation again. 

Since the latest release, we have found that our config is ignored for that module and it is always turned on. 

The advice we were given from the help desk was "as a SaaS customer, you cannot disable it on your own (this applies for any module really), you'd need to raise a request with us; and even if we disabled it, it would still be re-enabled during the next deployment."

It doesn't sound like a big issue, but it does get very confusing for users, as they assume there is an issue with the system.

it's just now part of the release process to go in and manually uninstall it but was just raising here in hopes that maybe it would not be a mandatory module in the future. 

If you need any more information, please reach out.

**Comment by simesy** [comment]
The change occurred over here https://github.com/govCMS/govcms8lagoon/pull/40

**Comment by stooit** [comment]
Housekeeping: Closing this one as it was resolved in https://github.com/govCMS/govcms8lagoon/pull/154
